#!/usr/bin/python3
"""

    @brief          Bag processing file whose settings are parsed from a yaml file.
                    The bag file contains calibration and processing data.

    @author         Patricio A. Vela,   pvela@gatech.edu
    @date           2022/07/01

"""
from benedict import benedict
import os

import glob
import shutil
import numpy as np
import os
import subprocess
import yaml
import threading
import time
import cv2
import matplotlib.pyplot as plt
import argparse
import copy
from pathlib import Path
import pickle

# ROS
import rospy
import rosgraph
import rosbag
from std_msgs.msg import UInt8

# Utils
from ROSWrapper.subscribers.Images_sub import Images_sub
from camera.utils.display import display_images_cv, display_rgb_dep_cv
from Surveillance.deployment.utils import display_option_convert, calc_closest_factors

# Surveillance system
from Surveillance.deployment.Base import BaseSurveillanceDeploy
from Surveillance.deployment.Base import Params as bParams
from Surveillance.deployment.utils import terminate_process_and_children
from Surveillance.deployment.activity_record import ActDecoder
from Surveillance.utils.imgs import draw_contour
from Surveillance.utils.specifications import specifications

# puzzle stuff
from puzzle.runner import RealSolver, ParamRunner
from puzzle.piece.template import Template, PieceStatus

# activity
from Surveillance.activity.state import StateEstimator
from Surveillance.activity.FSM import Pick, Place
from Surveillance.activity.utils import DynamicDisplay, ParamDynamicDisplay

# configs
#test_rgb_topic = "/test_rgb"
#test_dep_topic = "/test_depth"
#test_activity_topic = "/test_activity"
# @todo Eventually need to be in the configuration/specification.

# preparation
lock = threading.Lock()

timestamp_beginning = None
timestamp_ending = None
roscore_proc = None

# To be built
call_back_id = 0

def get_args():
    parser = argparse.ArgumentParser(
                            description="Run system on saved rosbag file.")
    parser.add_argument("yfile", type=str)
    args = parser.parse_args()
    return args

class ImageListener:
    def __init__(self, opt):

        self.opt = opt

        # Convert display code
        self.opt.general.display = display_option_convert(self.opt.general.display)

        # Initialize the saving folder

        if self.opt.output.save:
            if not self.opt.general.real_time:
                self.opt.output.path = Path(self.opt.rosbag_name).stem
            else:
                self.opt.output.path = 'realtime'

            # Clear up the space
            if os.path.exists(self.opt.output.path):
                shutil.rmtree(self.opt.output.path)
            os.makedirs(self.opt.output.path, exist_ok=True)

        # Data captured
        self.RGB_np = None
        self.D_np = None

        self.rgb_frame_stamp = None
        self.rgb_frame_stamp_prev = None

        # Initialize a node
        rospy.init_node("test_surveillance_on_rosbag")

        if self.opt.puzzle.solver_mode==1:
            mea_mode = 'sol'
        else:
            mea_mode = 'test'

        # Build up the surveillance system from the rosbag
        # @tod Hard-coded parameters should be in a yaml file.
        configs_surv = bParams(
            visualize=False,
            vis_calib=self.opt.general.vis_calib,
            ros_pub=False,
            # The calibration topics
            # deployment
            BEV_mat_topic="BEV_mat",
            intrinsic_topic="intrinsic",
            # scene interpreter
            empty_table_rgb_topic="empty_table_rgb",
            empty_table_dep_topic="empty_table_dep",
            glove_rgb_topic="glove_rgb",
            human_wave_rgb_topic="human_wave_rgb",
            human_wave_dep_topic="human_wave_dep",
            depth_scale_topic="depth_scale",
            # Postprocessing
            bound_limit = [200,200,50,50],
            mea_mode = mea_mode,
            mea_test_r = 150,
            mea_sol_r = 150,
            hand_radius = 200
        )

        # build the surveillance deployer
        self.surv = BaseSurveillanceDeploy.buildFromRosbag(conf.source.rosbag, configs_surv)

        # Build up the puzzle solver
        configs_puzzleSolver = ParamRunner(
            areaThresholdLower=1000, # @< The area threshold (lower) for the individual puzzle piece.
            areaThresholdUpper=8000, # @< The area threshold (upper) for the individual puzzle piece.
            pieceConstructor=Template,
            lengthThresholdLower=1000,
            BoudingboxThresh=(20, 100), # @< The bounding box threshold for the size of the individual puzzle piece.
            tauDist=100, # @< The radius distance determining if one piece is at the right position.
            hand_radius=200, # @< The radius distance to the hand center determining the near-by pieces.
            tracking_life_thresh=15, # @< Tracking life for the pieces, it should be set according to the processing speed.
            # solution_area=[600,800,400,650], # @< The solution area, [xmin, xmax, ymin, ymax]. We will perform frame difference in this area to locate the touching pieces.
            # It is set by the calibration result of the solution board.
        )
        self.puzzleSolver = RealSolver(configs_puzzleSolver)

        # State analysis
        self.state_parser = StateEstimator(
            signal_number=1,
            signal_names=["location"],
            state_number=1,
            state_names=["Move"],
            # move_th=50, # @< The threshold for determining the moving status. Note that this thresh only works well with low sampling rate.
            move_th=25,
        )

        # Initialize a subscriber
        Images_sub([self.opt.surveillance.rgb_topic,
                    self.opt.surveillance.depth_topic], 
                    callback_np=self.callback_rgbd)

        # Initialize the activity label subscriber, decoder, and
        # the label storage if needed
        self.activity_label = None
        if self.opt.activity.read:
            rospy.Subscriber(self.opt.activity.topic, UInt8, 
                             callback=self.callback_activity, queue_size=1)
            self.act_decoder = ActDecoder()

        # Activity analysis related
        # Initialized with NoHand
        self.move_state_history = None

        self.pick_model = Pick()
        self.place_model = Place()

        # Initialize fig for puzzle piece status display
        if self.opt.module.activity:
            self.status_window = None
            self.activity_window = None

        print("Initialization ready, waiting for the data...")

    def callback_rgbd(self, arg_list):

        if self.opt.general.verbose:
            print("Get to the callback")

        RGB_np = arg_list[0]
        D_np = arg_list[1]
        rgb_frame_stamp = arg_list[2].to_sec()

        # np.integer includes both signed and unsigned, whereas the np.int only includes signed
        if np.issubdtype(D_np.dtype, np.integer):
            if self.opt.general.verbose:
                print("converting the depth scale")
            D_np = D_np.astype(np.float32) * self.surv.depth_scale

        with lock:
            self.RGB_np = RGB_np.copy()
            self.D_np = D_np.copy()
            self.rgb_frame_stamp = copy.deepcopy(rgb_frame_stamp)
    
    def callback_activity(self, key_msg):
        # decode the activity
        key = chr(key_msg.data)
        self.act_decoder.decode(key)

        # store the activity label
        self.activity_label = self.act_decoder.get_activity()

    def run_system(self):

        with lock:

            global call_back_id

            if self.RGB_np is None:
                if self.opt.general.verbose:
                    print('No data')
                return

            rgb_frame_stamp = copy.deepcopy(self.rgb_frame_stamp)

            # Skip images with the same timestamp as the previous one
            if rgb_frame_stamp != None and self.rgb_frame_stamp_prev == rgb_frame_stamp:

                time.sleep(0.001)
                # if self.opt.general.verbose:
                #     print('Same timestamp')
                return
            else:
                self.rgb_frame_stamp_prev = rgb_frame_stamp
                RGB_np = self.RGB_np.copy()
                D_np = self.D_np.copy()
                activity = copy.deepcopy(self.activity_label)

            if self.opt.general.verbose:
                print("Running the Surveillance on the test data")

            if self.opt.output.save:
                # Save for debug
                cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_rgb.png'), self.RGB_np[:, :, ::-1])

            if self.opt.module.surveillance:
                self.surv.process(RGB_np, D_np)

                # For demo
                humanImg = self.surv.humanImg
                robotImg = self.surv.robotImg
                puzzleImg = self.surv.puzzleImg # @< Directly from surveillance system (without postprocessing)
                humanMask = self.surv.humanMask

                # For further processing
                postImg = self.surv.meaBoardImg
                visibleMask = self.surv.visibleMask
                hTracker = self.surv.hTracker
                hTracker_BEV = self.surv.scene_interpreter.get_trackers("human", BEV_rectify=True)  # (2, 1)

                if self.opt.output.save:
                    # Save for debug

                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_hand.png'),
                                humanImg[:, :, ::-1])
                    # cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_handMask.png'),
                    #             humanMask)
                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_puzzle.png'),
                                postImg[:, :, ::-1])
                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_visibleMask.png'),
                                visibleMask)

                    with open(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_hTracker.npy'), 'wb') as f:
                        np.save(f, hTracker_BEV)

            # Display
            if self.opt.general.display[0]:
                if self.activity_label is not None:
                    RGB_np_withLabel = cv2.putText(np.float32(RGB_np.copy()), self.activity_label, (10, 60), cv2.FONT_HERSHEY_SIMPLEX,
                                         2.0, (255, 0, 0), 5)
                    RGB_np_withLabel = np.uint8(RGB_np_withLabel)
                    display_images_cv([RGB_np_withLabel[:, :, ::-1]], ratio=0.5, window_name="Source RGB")
                else:
                    display_images_cv([RGB_np[:, :, ::-1]], ratio=0.5, window_name="Source RGB")
            if self.opt.general.display[1]:
                display_images_cv([humanImg[:, :, ::-1]], ratio=0.5, window_name="Hand layer")
            if self.opt.general.display[2]:
                display_images_cv([robotImg[:, :, ::-1]], ratio=0.5, window_name="Robot layer")
            if self.opt.general.display[3]:
                display_images_cv([puzzleImg[:, :, ::-1]], ratio=0.5, window_name="Puzzle layer")
            if self.opt.general.display[4]:
                display_images_cv([postImg[:, :, ::-1]], ratio=0.5, window_name="Postprocessing (Input to the puzzle solver)")

            # If there is at least one display command
            if any(self.opt.general.display):
                cv2.waitKey(1)

            if self.opt.module.analysis:
                # Hand moving states
                # Todo: here I only invoke the state parser when the hand is detected (hTracker is not None)
                # Todo: Should be moved to state parser in the future
                # This might cause non-synchronization with the puzzle states.
                # So might need to set the self.move_state to indicator value when the hand is not detected.
                if hTracker is None:
                    # -1: NoHand; 0: NoMove; 1: Move
                    self.move_state = -1

                    stateImg = cv2.putText(RGB_np.copy(), "No Hand", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 2.0, [255, 0, 0], 5)

                else:
                    # Get the tracker
                    self.state_parser.process([hTracker])
                    stateImg = self.state_parser.plot_states(RGB_np.copy())

                    # NOTE: The moving state is obtained here.
                    # The return is supposed to be of the shape (N_state, ), where N_state is the number of states,
                    # since it was designed to include extraction of all the states.
                    # Since the puzzle states is implemented elsewhere, the N_state is 1, hence index [0]
                    self.move_state = self.state_parser.get_states()[0]

                display_images_cv([stateImg[:, :, ::-1]], ratio=0.5, window_name="Move States")

                if self.opt.output.save:
                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_state.png'), stateImg[:, :, ::-1])

                print(f'Hand state: {self.move_state}')

            if self.opt.module.puzzle:
                # Work on the puzzle pieces

                if self.opt.puzzle.solver_mode == 0:
                    if call_back_id == 0:
                        # Initialize the SolBoard using the very first frame.
                        self.puzzleSolver.setSolBoard(postImg)

                        print(
                            f'Number of puzzle pieces registered in the solution board: {self.puzzleSolver.theManager.solution.size()}')

                        if self.opt.module.activity:
                            self.status_window = DynamicDisplay(
                                ParamDynamicDisplay(num=self.puzzleSolver.theManager.solution.size(),
                                                    window_title='Status Change'))
                            self.activity_window = DynamicDisplay(
                                ParamDynamicDisplay(num=self.puzzleSolver.theManager.solution.size(),
                                                    status_label=['NONE', 'MOVE'], ylimit=1,
                                                    window_title='Activity Change'))

                        # # Debug only
                        if self.opt.general.verbose:
                            cv2.imshow('debug_source', RGB_np[:, :, ::-1])
                            cv2.imshow('debug_humanMask', humanMask)
                            cv2.imshow('debug_puzzleImg', puzzleImg[:, :, ::-1])
                            cv2.imshow('debug_postImg', postImg[:, :, ::-1])
                            cv2.imshow('debug_solBoard', self.puzzleSolver.theManager.solution.toImage(ID_DISPLAY=True)[:, :, ::-1])
                            cv2.waitKey()
                    # Plan not used yet
                    plan = self.puzzleSolver.process(postImg, visibleMask, hTracker_BEV)

                elif self.opt.puzzle.solver_mode == 1:
                    # Calibration process
                    # Plan not used yet
                    plan = self.puzzleSolver.calibrate(postImg, visibleMask, hTracker_BEV)
                elif self.opt.puzzle.solver_mode == 2:
                    
                    # Initialize the SolBoard with saved board at the very first frame.
                    if call_back_id == 0:
                        self.puzzleSolver.setSolBoard(postImg, self.opt.source.puzzle)

                        print(
                            f'Number of puzzle pieces registered in the solution board: {self.puzzleSolver.theManager.solution.size()}')

                        if self.opt.module.activity:
                            self.status_window = DynamicDisplay(
                                ParamDynamicDisplay(num=self.puzzleSolver.theManager.solution.size(),
                                                    window_title='Status Change'))
                            self.activity_window = DynamicDisplay(
                                ParamDynamicDisplay(num=self.puzzleSolver.theManager.solution.size(),
                                                    status_label=['NONE', 'MOVE'], ylimit=1,
                                                    window_title='Activity Change'))

                        # # Debug only
                        if self.opt.general.verbose:
                            cv2.imshow('debug_source', RGB_np[:, :, ::-1])
                            cv2.imshow('debug_humanMask', humanMask)
                            cv2.imshow('debug_puzzleImg', puzzleImg[:, :, ::-1])
                            cv2.imshow('debug_postImg', postImg[:, :, ::-1])
                            cv2.imshow('debug_solBoard',
                                       self.puzzleSolver.theManager.solution.toImage(ID_DISPLAY=True)[:, :, ::-1])
                            cv2.waitKey()

                    # Plan not used yet
                    plan = self.puzzleSolver.process(postImg, visibleMask, hTracker_BEV)
                    print(plan)
                    cv2.waitKey()
                else:
                    raise RuntimeError('Wrong puzzle.solver_mode!')

                if self.opt.general.display[5]:
                    # Display measured/tracked/solution board
                    # display_images_cv([self.puzzleSolver.bMeasImage[:, :, ::-1], self.puzzleSolver.bTrackImage[:, :, ::-1], self.puzzleSolver.bSolImage[:, :, ::-1]],
                    #                   ratio=0.5, window_name="Measured/Tracking/Solution board")

                    # Display the original measured/tracked(ID from solution board)/solution board
                    display_images_cv(
                        [self.puzzleSolver.bMeasImage[:, :, ::-1], self.puzzleSolver.bTrackImage_SolID[:, :, ::-1],
                         self.puzzleSolver.bSolImage[:, :, ::-1]],
                        ratio=0.5, window_name="Measured/Tracked/Solution board")

                    cv2.waitKey(1)

                if self.opt.puzzle.solver_mode != 1 and self.opt.output.save:
                    # Save for debug
                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_bMeas.png'), self.puzzleSolver.bMeasImage[:, :, ::-1])
                    cv2.imwrite(os.path.join(self.opt.output.path, f'{str(call_back_id).zfill(4)}_bTrack_SolID.png'), self.puzzleSolver.bTrackImage_SolID[:, :, ::-1])

                # Compute progress
                # Note that the solution board should be correct, otherwise it will fail.
                if self.opt.puzzle.solver_mode != 1:
                    try:
                        thePercent = self.puzzleSolver.progress(USE_MEASURED=False)
                        print(f"Progress: {thePercent}")
                    except:
                        print('Double check the solution board to make it right.')

            if self.opt.module.activity:

                # TODO: Need to be moved to somewhere else
                status_data = np.zeros(len(self.puzzleSolver.thePlanner.status_history))
                activity_data = np.zeros(len(self.puzzleSolver.thePlanner.status_history))

                for i in range(len(status_data)):
                    try:
                        status_data[i] = self.puzzleSolver.thePlanner.status_history[i][-1].value
                    except:
                        status_data[i] = PieceStatus.UNKNOWN.value

                    # Debug only
                    # if len(self.puzzleSolver.thePlanner.status_history[i])>=2 and \
                    #         np.linalg.norm(self.puzzleSolver.thePlanner.loc_history[i][-1] - self.puzzleSolver.thePlanner.loc_history[i][-2]) > 10:
                    #     print('!')

                    if len(self.puzzleSolver.thePlanner.status_history[i])>=2 and \
                        self.puzzleSolver.thePlanner.status_history[i][-1] == PieceStatus.MEASURED and \
                            self.puzzleSolver.thePlanner.status_history[i][-2] != PieceStatus.MEASURED and \
                                np.linalg.norm(self.puzzleSolver.thePlanner.loc_history[i][-1] - self.puzzleSolver.thePlanner.loc_history[i][-2]) > 30:
                            activity_data[i]= 1
                            print('Move activity detected.')

                    else:
                        activity_data[i]= 0

                self.status_window((call_back_id, status_data))
                self.activity_window((call_back_id, activity_data))

            print(f"The processed test frame id: {call_back_id} ")
            call_back_id += 1

        # Only applied when working on rosbag playback
        if self.opt.general.real_time is False:

            global timestamp_beginning
            global timestamp_ending
            global roscore_proc

            print(f'Current frame time: {np.round(rgb_frame_stamp-timestamp_beginning,2)}s')
            print('\n\n')

            # # Debug only
            if self.opt.general.verbose:
                print(f'Last frame time: {np.round(timestamp_ending-timestamp_beginning,2)}s')

            # We ignore the last 2 seconds
            if timestamp_ending is not None and abs(rgb_frame_stamp - timestamp_ending) < 2:

                if self.opt.puzzle.solver_mode == 1:
                    # Only for calibration process
                    if self.puzzleSolver.theCalibrated.size() > 0:
                        # Save for future usage
                        with open(self.opt.source.puzzle, 'wb') as fp:
                            pickle.dump(self.puzzleSolver.theCalibrated, fp)

                        print(f'Number of puzzle pieces registered in the solution board: {self.puzzleSolver.theCalibrated.size()}')
                        print(f'Bounding box of the solution area: {self.puzzleSolver.theCalibrated.boundingBox()}')
                        cv2.imshow('debug_solBoard', self.puzzleSolver.theCalibrated.toImage(ID_DISPLAY=True)[:, :, ::-1])
                        cv2.waitKey()
                    else:
                        print('No piece detected.')

                print('Shut down the system.')
                rospy.signal_shutdown('Finished')
                # Stop the roscore if started from the script
                if roscore_proc is not None:
                    terminate_process_and_children(roscore_proc)
        else:
            print('\n\n')


if __name__ == "__main__":

    args = get_args()                           # parse argument. 
    conf = specifications.load(args.yfile)      # load yaml specifications.

    # update the args about the existence of the activity topic
    bag = rosbag.Bag(conf.source.rosbag)

    # @todo   If check below not so consistent with yaml loading.
    #         Need to first check if it is a field.
    if ('topic' in conf.activity) and (len(list(bag.read_messages(conf.activity.topic))) != 0) :
        conf.activity.read = True
    else:
        conf.activity.read = False

    if conf.general.restart:
        subprocess.call(['killall rosbag'], shell=True)
        subprocess.call(['killall rosmaster'], shell=True)

    # Start the roscore if not enabled
    if not rosgraph.is_master_online():
        roscore_proc = subprocess.Popen(['roscore'], shell=True)
        # wait for a second to start completely
        time.sleep(1)

    listener = ImageListener(conf)

    plt.ion()
    if conf.general.real_time is False:
        # Get basic info from the rosbag
        info_dict = yaml.safe_load(
            subprocess.Popen(['rosbag', 'info', '--yaml', conf.source.rosbag], stdout=subprocess.PIPE).communicate()[0])

        timestamp_beginning= info_dict['start']
        timestamp_ending = info_dict['end']

        print('Playback the rosbag recordings')

        # Need to start later for initialization
        # May need to slow down the publication otherwise the subscriber won't be able to catch it
        # -d:delay; -r:rate; -s:skip; -q no console display
        command = "rosbag play {} -d 2 -r 1 -s 15 -q --topic {} {} {}".format(conf.source.rosbag, conf.surveillance.rgb_topic,conf.surveillance.depth_topic, conf.activity.topic)

        print('============')
        print(command)
        print('============')
        try:
           # Be careful with subprocess, pycharm needs to start from the right terminal
           # environment (.sh instead of shortcut).
           # See https://stackoverflow.com/a/3478415
           # We do not want to block the process
           subprocess.Popen(command, shell=True)
        except:
           print("Cannot execute the bash command: \n {}".format(command))
           exit()

    while not rospy.is_shutdown():
        listener.run_system()

    if conf.output.save and conf.general.debug_individual_folder:
        # Mainly for debug
        def resave_to_folder(target):
            file_list = glob.glob(os.path.join(listener.opt.output.path, f'*{target}.png'))

            if os.path.exists(f'{target}'):
                shutil.rmtree(f'{target}')
            os.makedirs(f'{target}', exist_ok=True)

            for file_path in file_list:
                shutil.copyfile(file_path, os.path.join(f'{target}', os.path.basename(file_path)))

        target_list = ['bTrack_SolID']

        for i in target_list:
            resave_to_folder(i)




#    parser.add_argument("--fDir", type=str, default="./",
#                        help="The folder's name.")
#    parser.add_argument("--rosbag_name", type=str, default="data/Testing/Adan/data_2022-05-06-11-09-27_Heather_Cupcake_Compressed.bag", \
#                        help="The rosbag file name.")
#    parser.add_argument("--real_time", action='store_true',
#                        help="Whether to run the system for real-time or just rosbag playback instead.")
#    parser.add_argument("--force_restart", action='store_true',
#                        help="Whether force to restart the roscore.")
#    parser.add_argument("--vis_calib", action='store_true', default=False, \
#                        help="Visualize the calibration process.")
#    parser.add_argument("--display", default="001000", \
#                        help="0/000000: No display;"
#                             "1/000001: source input;"
#                             "2/000010: hand;"
#                             "4/000100: robot;"
#                             "8/001000: puzzle;"
#                             "16/010000: postprocessing;"
#                             "32/100000: puzzle board;"
#                             "You can use decimal or binary as the input.")
#    parser.add_argument("--survelliance_system", action='store_true',
#                        help="Whether to apply survelliance_system.")
#    parser.add_argument("--puzzle_solver", action='store_true',
#                        help="Whether to apply puzzle_solver.")
#    parser.add_argument("--puzzle_solver_mode", default=0,
#                        help="0: Set the first frame as the solution img;"
#                             "1: Calibration based on a rosbag recording;"
#                             "2: Run on the rosbag recording assuming the calibration board is already saved.")
#    parser.add_argument("--puzzle_solver_SolBoard", default='caliSolBoard.obj',
#                        help="The saving path to a .obj instance")
#    parser.add_argument("--state_analysis", action='store_true',
#                        help="Whether to apply the state analysis. Display is automatically enabled.")
#    parser.add_argument("--activity_interpretation", action='store_true',
#                        help="Whether to interpret the human's activity. Display is automatically enabled.")
#    parser.add_argument("--verbose", action='store_true',
#                        help="Whether to debug the system.")
#    parser.add_argument("--save_to_file", action='store_true',
#                        help="Whether save to files, the default file location is the same as the rosbag or realtime.")
#    parser.add_argument("--debug_individual_folder", action='store_true',
#                        help="Whether save files into different folders. More convenient for debug.")
